name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B -DskipTests clean package
      - name: Run Tests (headless)
        run: mvn -B test

